spring.application.name=smart-societies
server.port=8080
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/smart_society}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:new_password}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.write-dates-as-timestamps=false
app.jwt.secret=${JWT_SECRET:mySuperSecretKeyForSmartSocietyBackendTesting}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
